version: "3"
services:
  hackathon-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hackathon-app
    environment:
      POSTGRES_USER: ""
      POSTGRES_PASS: ""
      POSTGRES_DB: ""
      POSTGRES_HOST: ""
      JWT_SECRET: ""
    ports:
      - "8000:8000"
    networks:
      - hackathon-network

  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_hackathon_tables.sql
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: ""
      POSTGRES_DB: ""
    expose:
    - "5432"
    command: -p 5432
    ports:
      - "5432:5432"
    networks:
      - hackathon-network

volumes:
  pgdata:

networks:
  hackathon-network:
    driver: bridge